### PR TITLE
Add templates

### PR DESCRIPTION
**Pull request by CogJoel**

### CODE REVIEW

**Review by spex66 — COMMENTED** [review]
@CogJoel thx for the PR!

- you're sure about the lower/upper cases? The list is case sensitive
- do you have a documentation pointer, where these ACLs are mentioned?
- and they support dataset-scoping? Otherwise we need to add them to "all scope only list" too
(Ok mobile atm, hard to check details on my own)

**Comment by CogJoel** [comment]
> @CogJoel thx for the PR!
> 
> * you're sure about the lower/upper cases? The list is case sensitive
> * do you have a documentation pointer, where these ACLs are mentioned?
> * and they support dataset-scoping? Otherwise we need to add them to "all scope only list" too
>   (Ok mobile atm, hard to check details on my own)

Changed to biggerCase after testing the Api :)

**Comment by spex66** [comment]
@CogJoel / @tugceozgur 
For semantic versioning:
1. `__version__` in init.py needs to be updated to 2.2.0
2. Commit message must start with *feat*, like
```
feat(acls): two new ACLs
- list them
```

Only then the new release v2.2.0 will be automatically generated


When Joel's local test succeeds you can merge

**Review by spex66 — APPROVED** [review]
added two more acls (for fdm) which are expected to not doing harm for non-fdm projects
- bumped version number to 2.2.0

**Pull request merged**
