### PR TITLE
updates and adding --with-special-groups support

### PR DESCRIPTION
**Pull request by spex66**
reference: #8 
version: 1.2.0
changelog: 
- added a new `deploy` parameter to cli and gh-action: `--with-special-groups [yes|no]`
- from `--help`:
```text
Usage: bootstrap-cli deploy [OPTIONS] [CONFIG_FILE]

  Deploy a set of bootstrap from a config-file

Options:
  --debug                         Print debug information
  --with-special-groups [yes|no]  Create special CDF Groups, which don't have
                                  capabilities (extractions, transformations)
  -h, --help                      Show this message and exit.
```

### CODE REVIEW

**Comment by spex66** [comment]
main job was adding the `--with-special-groups` click parameter
- adding it to methods
- providing support for it in `actions.yml`
- decision to make it a `yes/no` string parameter was, because gh-action manifest, seems to lack support for boolean switches, so that was the simplest solution

Implementation refactored part from `process_group(..)` into reusable `create_group(..)`
- and used it for new `generate_special_groups(..)`

**Review by tugceozgur — COMMENTED** [review]
Also update the version 1.2.0 to pyproject.toml :)

**Review by tugceozgur — APPROVED** [review]
looks great :)

**Comment by spex66** [comment]
- stopped trying to make the `__init__.py > __version__` automatically set by `pyproject.toml` as this failed in docker-build (which is not running a `poetry install` but a `pip install requirements.txt`
- configured the version now manually in these two places
- upgrade py from 3.7 to 3.9

**Pull request merged**
